### LOGIN

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "phoneNumber": "09514406062",
    "password": "ryuzaki"
}




### PROTECTED ROUTE
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZU51bWJlciI6IjA5NTE0NDA2MDYyIiwicGFzc3dvcmQiOiJyeXV6YWtpIiwiaWF0IjoxNzYwODQzOTIxLCJleHAiOjE3NjA4NDQ4MjF9.GvP3eP9CycU7ueZs0mzyFN823hRK123wdKH7Nj-PN8c

### REFRESH ACCESS TOKEN 

POST http://localhost:3000/auth/refresh-access-token