### LOGIN

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "light@gmail.com",
    "password": "123"
}

### SETIING NEW PASSWORD

POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "newPassword": "123",
    "otp": "rtrtrt",
    "email": "jhonwellssespanola4@gmail.com"
}




### REGISTER
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "ryu@gmail.com",
    "password": "123",
    "firstName": "L",
    "lastName": "lawliet"
}